# Generated by Django 4.1.6 on 2023-02-11 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NGOAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='organisation',
            name='goal',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ngo_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='Philanthropist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1000)),
                ('email', models.CharField(default='', max_length=1000)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
