# Generated by Django 4.1.6 on 2023-02-11 10:46

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NGOAPP', '0002_organisation_email_organisation_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=1000)),
                ('caption', models.TextField(default='')),
                ('image', models.ImageField(upload_to='post_images')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='organisation',
            name='ngo_type',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
