# Generated by Django 4.1.6 on 2023-02-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGOAPP', '0003_post_organisation_location_organisation_ngo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='./media/post_images'),
        ),
    ]
